### ISSUE TITLE
can't parse some URL

### ISSUE THREAD

**Issue by command-z-z** [catppuccin/github#37] opened 2022-11-17 08:35 UTC
when i use github theme by stylus extension, I can enjoy this theme very comfortably. 
however, i can't parse this URL `https://www.zhihu.com/` very well 
![Screenshot from 2022-11-17 16-33-54](https://user-images.githubusercontent.com/71259900/202396534-979dd4e4-5a3a-4198-9cd7-7fd778417c70.png)

how can i solve this problem? ths

**Comment by justTOBBI** [comment] 2022-11-17 11:34
And you are sure its the github theme thats causing this?

**Comment by command-z-z** [comment] 2022-11-17 11:39
> And you are sure its the github theme thats causing this?

yes, when I turn this style off, the site becomes normal:)

**Comment by justTOBBI** [comment] 2022-11-17 12:29
Thats weird. Could be the RegEx ig

**Comment by tuhanayim** [comment] 2022-11-29 20:58
> > And you are sure its the github theme thats causing this?
> 
> yes, when I turn this style off, the site becomes normal:)

I can't reproduce the same behaviour.

> Thats weird. Could be the RegEx ig

It's not, it doesn't capture the site.
![image](https://user-images.githubusercontent.com/108196023/204645966-0c7854e1-5ffc-4a85-9679-053bc8c41489.png)

**Comment by nekowinston** [comment] 2022-12-13 00:17
Hi there!

I just pushed (#41) because the Stylus theme was applying some styles globally. This should be fixed now, please let us know if the issue persists.

**Closed by nekowinston** 2022-12-13 00:17 UTC
