### ISSUE TITLE
Legibility issues in diffs

### ISSUE THREAD

**Issue by jeffijoe** [catppuccin/github#27] opened 2022-09-13 14:09 UTC
Loving this theme, nice work! 🔥 

Not sure if this is the right place to report this, but I ran into this while reviewing a PR. Notice how the content of the highlighted selection is difficult to read (the `7d`).

<img width="353" alt="image" src="https://user-images.githubusercontent.com/2505474/189922992-05289853-2765-4ae9-964a-9503dbbd74e0.png">

**Comment by andreasgrafen** [comment] 2022-09-13 15:21
Nice to hear you enjoy the theme; and no worries, this is the perfect place to report this. ^—^
I'm actually not quite sure what the best way to fix this would be tho.. but I'll look into it. Thanks for letting me/us know.

**Comment by jeffijoe** [comment] 2022-09-13 15:25
Implementation-wise I am not sure either, but I think perhaps changing this particular instance to `Base` seems to help a bit:

<img width="539" alt="image" src="https://user-images.githubusercontent.com/2505474/189942329-33482787-c156-47d5-8b0b-99761244822a.png">

**Comment by andreasgrafen** [comment] 2022-09-13 16:05
It still doesn't seem to hit any contrast checks. It is better for sure, but still hard to make out on a quick glance.. tho still better than nothing. :D

**Comment by andreasgrafen** [comment] 2022-09-13 17:38
Okay, so I have [this very serious pull request](https://github.com/andreasgrafen/dummy_thicc/pull/1/files) to try and figure out a solution. The issue is, that I don't even run into the same problem you run into. D:

![](https://cdn.discordapp.com/attachments/907386197855322123/1019290944039833630/Screenshot_2022-09-13_at_18.58.13.png)

**Comment by jeffijoe** [comment] 2022-09-13 18:19
Did you highlight (with the cursor) the `7d`, or was the `7d` the exact range that changed in your diff? My screenshot is for the latter.

**Comment by andreasgrafen** [comment] 2022-09-13 18:50
Oh! My bad, I read that as a regular selection.
[This](https://github.com/andreasgrafen/dummy_thicc/pull/2/files) now captures the issue. Thanks again. :3

**Comment by andreasgrafen** [comment] 2022-09-16 11:31
@jeffijoe heya! I think I found a way that fixes this without breaking on the dark themes. Feel free to give it a test drive and let me know what you think. c:

<img width="636" alt="Screenshot 2022-09-16 at 13 29 44" src="https://user-images.githubusercontent.com/35840154/190629276-1b1c5ce1-018e-471b-9a82-b3e7ec9787af.png">

**Comment by jeffijoe** [comment] 2022-09-16 13:45
That looks great! Ship it! :shipit:

**Comment by jeffijoe** [comment] 2022-09-16 13:46
Completely random, but I just noticed this too 😂  The @andreasgrafen (mention) highlighting looks a bit weird on the light theme 😅 

<img width="257" alt="image" src="https://user-images.githubusercontent.com/2505474/190653560-52fdef13-0b98-4093-9005-537fe0ed8669.png">

**Comment by andreasgrafen** [comment] 2022-09-16 16:42
I'll merge the changes into main in a bit.
As for the other things - the Actions def. need fixing. I'd suggest opening a new Issue to track that, but I can also do that once I'm on the train. The Github mobile app is just ... built different. xd

**Comment by andreasgrafen** [comment] 2022-09-16 18:16
closed as per #29. c:

**Closed by andreasgrafen** 2022-09-16 18:16 UTC
